### ISSUE TITLE
Discussion and suggestions

### ISSUE THREAD

**Issue by ashwin2802** [rohanblueboybaijal/ariitk_template#2]
Plis add support for other shells, not just bash ( i can't test because i don't have bashrc :( )

Each package will have only one node executable which is the name of the package, so i don't think node name is needed in the template. same for default library we can set it to be same as the package name, user can change if needed.

More importantly, why are you copying the scripts into the ~/bin and editing the executable paths and stuff? these scripts are use and throw, and the scripts directory should ideally be deleted once setup is over. so you can directly make the executables in that directory and use those right? editing the user bash profiles and executable PATH is *not* a good idea imho.

For final deployment (this might be a little extreme automation but) should we have a one-line no setup installation? (like gazebo for instance). With Github CLI even new repos can be created on the remote from the command line, so we can directly just curl the script and do all the setup. What do you guys think?

@rohanblueboybaijal  @varunk122 

PS: tell me if you need help somewhere, bit free from the resume stuff now :)

**Comment by rohanblueboybaijal** [comment]
So as of now, we're assuming the user always keeps a copy of the template repo somewhere is his/her computer. 

And then we've created these custom commands. 

You're suggesting we do away with the ariitk_commands and permanent template repo?

**Comment by rohanblueboybaijal** [comment]
I was slightly apprehensive about editing the paths and bin. 

But these commands did seem pretty convenient.

**Comment by varunk122** [comment]
I think making this pkg one time clone is better than curling it everytime. For example,

If you need to make a new library for your node , you can run `ariitk_create_lib <lib_name>` and you are done with both header and cpp file for the library.

Similarly , sometimes you need to make a new pkg for testing a feature that you can't check in any of the existing pkg , then run ariitk_create_pkg and you are done. 

better than curling everytime and then run commands

For testing purpose you can run `exec bash` command on your  zsh terminal because we have to fix some errors which these scripts throw when we use shebang #!/bin/sh.

and we have used node_name in config.sh file to give users more freedom to have different executable node names and file names. File name will be a directory name but you can choose a different executable name if you want to .

Now , we are trying to make a cpp_binding for our shell scripts to parse a yaml file to setup the required configurations instead of a sh file.

**Comment by ashwin2802** [comment]
@varunk122 i don't have bash profiles and stuff so even `exec bash` doesn't cut it

and ig let's discuss the one time clone wala thing on a call tomorrow

**Comment by varunk122** [comment]
@ashwin2802 @rohanblueboybaijal 

I have written a script ariitk_create pkg which will create a meta pkg , set your remote as well.
You just have to run this command `wget https://tinyurl.com/ariitk && chmod +x ariitk && ./ariitk && rm -rf ariitk` , it will also create a workspace.

But , before using this command you must have a repository on github as your main_pkg_name(which contains your other pkgs).

I have also tried to automate the process of creating a repository as well ------>

I can use curl command to fill the blanks like repository name ,etc like we use curl command to login to a webpage.I mean to say that I can just use curl command to fill the the value of required javascript tags and create a repository , and i tried the same ,check the inspect element of the page for a while , but i was unable to do it.

Using github api to create a repository . 

` You may create a repository on GitHub either from an internet browser or using the GitHub command line API as follows:
curl -u 'USER' https://api.github.com/user/repos -d '{"name":"REPO"}'  `

But this command will ask users their github password . So this is not a good way to solve this problem. Also github is going to deprecate the above command after some time and will replace the command with a similar command , about which you can read it from here -> https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

**Comment by ashwin2802** [comment]
more shorter: just pipe the main script to sh like: `wget https://tinyurl.com/ariitk | sh` . It won't store itself so no need to delete
for clone by CLI check the newly released CLI: [github.com/cli/cli](https://github.com/cli/cli)

**Comment by varunk122** [comment]
@ashwin2802 
I have added github CLI feature to the ariitk_pkg script as well as added zsh compatibility. I have tested the script on my zsh terminal. Please check the script on your computer. You have to install github CLI by your own.
